### PR TITLE
feat: created a standard for commits

### PR DESCRIPTION
**Pull request by EduardoAraujoB**
Solves #28

### CODE REVIEW

**Comment by lucasmontano** [comment]
That's very nice! Should we add something to the ReadMe? Like this [link](https://www.conventionalcommits.org/en/v1.0.0/)

So beginners can understand why the Lint is failing upfront :)

**Comment by EduardoAraujoB** [comment]
Okay, I will update the documentation

**Comment by EduardoAraujoB** [comment]
I thought on it, but the commitizen will be the process to create a commit more verbose and don't is necessary for this project

**Comment by omurilo** [comment]
> So it's good. Maybe when should put package-lock.json in .gitignore.

Hi bro! the lock files should not be ignored, [check the oficial doc of npm](https://github.com/npm/npm/blob/v5.0.0/doc/files/package-lock.json.md)

**Comment by nataneb32** [comment]
Okay. Thank you for explaining.

**Pull request merged**
